# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "raid0"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/231df372-aa68-4dc8-b44c-8b39695b9daf";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1EE7-0310";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # RAID 0 stripe across the two 3.6 TB SSDs (Samsung 870 EVO + Crucial MX500),
  # ~7.2 TB usable, LUKS-encrypted, used as a Longhorn disk. No local redundancy
  # by design: Longhorn replicates across nodes, so these disks only hold
  # redundant copies. NixOS assembles the array at boot but does NOT open the
  # LUKS device or mount it — that is manual (see below), so boot/SSH never wait
  # on a passphrase and K3s still starts normally. The Longhorn disk on this
  # array simply stays unavailable until you unlock it.
  #
  # After every reboot, SSH in and run:
  #   sudo cryptsetup luksOpen /dev/md0 longhorn-raid0
  #   sudo mount /mnt/longhorn-server-raid0
  #
  # One-time provisioning (already done):
  #   sudo cryptsetup luksFormat /dev/md0
  #   sudo cryptsetup luksOpen /dev/md0 longhorn-raid0
  #   sudo mkfs.ext4 -L longhorn-raid0 /dev/mapper/longhorn-raid0
  boot.swraid = {
    enable = true;
    mdadmConf = ''
      MAILADDR root
      ARRAY /dev/md0 metadata=1.2 UUID=aa741cb2:05167c9e:5c1746f5:9afc442f
    '';
  };

  # noauto + nofail: never block boot; mounted by hand after luksOpen.
  fileSystems."/mnt/longhorn-server-raid0" = {
    device = "/dev/mapper/longhorn-raid0";
    fsType = "ext4";
    options = [
      "noatime"
      "noauto"
      "nofail"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
